# Generated by Django 2.2.7 on 2019-12-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='url_title',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
